name: CI/CD Pipeline with Flaky Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest test_flaky.py
        continue-on-error: true

      - name: Retry flaky tests if failed
        if: failure()
        run: pytest --reruns 3 test_flaky.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Deploy (Mock)
        run: echo "Deploying... Success!"
